# Warehouse Analysis Notebook

This notebook loads the flattened Parquet tables from the Data Warehouse and displays them.

**Tables:** `genes`, `gene_seeds`, `powers`, `power_seeds`, `gene_regulation`, `gene_side_effects`.

In [1]:
import os
import sys
from pyspark.sql import SparkSession
import pandas as pd

# Ensure we can import our modules
# sys.path.append(os.path.abspath("../super-services/src")) # Adjust if needed

from super.core.runtime import bootstrap_spark_env
from super.core import utils
from super.core.display import display_scrollable_dataframe

In [2]:
# Initialize Spark Session
bootstrap_spark_env()

spark = (SparkSession.builder
.appName("WarehouseViewer")
.config("spark.executor.memory", "4g")
.config("spark.driver.memory", "4g")
.getOrCreate())

WARNING: Using incubator modules: jdk.incubator.vector
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/01/19 02:35:21 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
26/01/19 02:35:21 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
26/01/19 02:35:21 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.

In [3]:
# Load Configuration
conf = utils.get_app_conf("generate_powers")
stage_root = conf.get_string("stage_root")
warehouse_root = os.path.join(stage_root, "warehouse")

print(f"Reading Warehouse from: {warehouse_root}")

Reading Warehouse from: /home/gideon/tmp/super_powers/data/warehouse

## 1. Genes Table

In [4]:
genes_df = spark.read.parquet(os.path.join(warehouse_root, "genes"))
display_scrollable_dataframe(genes_df.toPandas())

VBox(children=(HTML(value='\n    <style>\n      #scrollable_container_7128ebfbbbc2468cb73d5519b3295f37 {\n    …

## 2. Powers Table

In [5]:
powers_df = spark.read.parquet(os.path.join(warehouse_root, "powers"))
display_scrollable_dataframe(powers_df.toPandas())

VBox(children=(HTML(value='\n    <style>\n      #scrollable_container_568f4b568f6b4188ae17332fe1d07559 {\n    …

## 3. Link Tables
**Gene Seeds, Power Seeds, Side Effects**

In [6]:
gene_seeds_df = spark.read.parquet(os.path.join(warehouse_root, "gene_seeds"))
display_scrollable_dataframe(gene_seeds_df.limit(100).toPandas())

,gene_id,seed_name,role,weight
0,ELASTI-569,Elastic Physiology,primary,0.70
1,ELASTI-569,Rubber Physiology,primary,0.20
2,HAMMER-783,Hammerspace Access,primary,0.70
3,HAMMER-783,Probability Manipulation,primary,0.20
4,COSMIC-745,Cosmic Empowerment,primary,0.70
5,COSMIC-745,Regeneration,primary,0.15
6,COSMIC-745,Narrative Awareness,primary,0.15
7,REGENE-986,Regeneration,primary,0.60
8,REGENE-986,Mythic Invulnerability,primary,0.40
9,REGENE-494,Regeneration,primary,0.75
10,REGENE-494,Mutant Detection,primary,0.15
11,POCKET-281,Pocket Dimension Access,primary,0.70
12,POCKET-281,Hammerspace Access,primary,0.30
13,FLIGHT-GLIDE,Flight,primary,0.70
14,FLIGHT-GLIDE,Protean Shapeshifting,primary,0.20
15,SEADOM-168,Sea Dominion,primary,0.75
16,SEADOM-168,Force Field Generation,primary,0.15
17,TELEKI-495,Telekinesis,primary,0.70
18,TELEKI-495,Concept Suppression,primary,0.20
19,TELEKI-495,Weather Control,primary,0.10
20,SEADOM-722,Sea Dominion,primary,0.70
21,SEADOM-722,Protean Shapeshifting,primary,0.30
22,SUPERS-929,Super Speed,primary,0.70
23,SUPERS-929,Time Manipulation,primary,0.25
24,PAINTE-527,Painted Reality Traversal,primary,0.70
25,PAINTE-527,Wall Crawling,primary,0.20
26,IMAGIN-902,Imagination Materialization,primary,0.70
27,IMAGIN-902,Delayed Consequences,primary,0.20
28,TELEKI-219,Telekinesis,primary,0.70
29,TELEKI-219,Imagination Materialization,primary,0.30
30,HAMMER-321,Hammerspace Access,primary,0.70
31,HAMMER-321,Probability Manipulation,primary,0.30
32,OPTICE-847,Optic Energy Emission,primary,0.70
33,OPTICE-847,Force Field Generation,primary,0.30
34,ELASTI-658,Elastic Physiology,primary,0.70
35,ELASTI-658,Rubber Physiology,primary,0.30
36,PAINTE-652,Painted Reality Traversal,primary,0.70
37,SEADOM-882,Sea Dominion,primary,0.80
38,SEADOM-882,Gravity Forgetfulness,primary,0.20
39,SUPERS-813,Super Speed,primary,0.85
40,SUPERS-813,Heroic Strength,primary,0.15
41,IRRESI-582,Irresistible Allure,primary,0.70
42,IRRESI-582,Enhanced Senses,primary,0.30
43,MATTER-347,Matter Manipulation,primary,0.70
44,MATTER-347,Time Manipulation,primary,0.15
45,MATTER-347,Delayed Consequences,primary,0.15
46,REGENE-235,Regeneration,primary,0.80
47,REGENE-235,Time Manipulation,primary,0.20
48,IRRESI-985,Irresistible Allure,primary,0.80
49,DIVINE-712,Divine Lightning,primary,0.70
50,DIVINE-712,Mystic Arts,primary,0.30
51,POCKET-951,Pocket Dimension Access,primary,0.75
52,POCKET-951,Hammerspace Access,primary,0.25
53,TIMEMA-789,Time Manipulation,primary,0.80
54,TIMEMA-789,Reality Anchoring,primary,0.20
55,MUTANT-537,Mutant Detection,primary,0.70
56,MUTANT-537,Prophetic Sight,primary,0.20
57,PHASIN-348,Phasing,primary,0.70
58,PHASIN-348,Toon Force,primary,0.30
59,PAINTE-401,Painted Reality Traversal,primary,0.70
60,PAINTE-401,Probability Manipulation,primary,0.30
61,OPTICE-782,Optic Energy Emission,primary,0.70
62,OPTICE-782,Probability Manipulation,primary,0.30
63,ANVILM-256,Anvil Magnetism,primary,0.70
64,ANVILM-256,Cosmic Empowerment,primary,0.30
65,SEADOM-297,Sea Dominion,primary,0.65
66,SEADOM-297,Weather Control,primary,0.25
67,MYSTIC-814,Mystic Arts,primary,0.70
68,MYSTIC-814,Reality Anchoring,primary,0.30
69,FLIGHT-547,Flight,primary,0.70
70,FLIGHT-547,Gravity Forgetfulness,primary,0.20
71,IMAGIN-499,Imagination Materialization,primary,0.70
72,IMAGIN-499,Heroic Strength,primary,0.20
73,SUPERB-487,Super Breath,primary,0.70
74,SUPERB-487,Time Manipulation,primary,0.20
75,SUPERS-669,Super Speed,primary,0.85
76,SUPERS-669,Optic Energy Emission,primary,0.15
77,PHASIN-989,Phasing,primary,0.80
78,PHASIN-989,Reality Anchoring,primary,0.20
79,OPTICE-347,Optic Energy Emission,primary,0.70
80,OPTICE-347,Irresistible Allure,primary,0.30
81,NARRAT-913,Narrative Awareness,primary,0.70
82,NARRAT-913,Rule Awareness,primary,0.30
83,SUPERL-757,Super Leaping,primary,0.70
84,SUPERL-757,Force Field Generation,primary,0.15
85,SUPERL-757,Regeneration,primary,0.15
86,INVOLU-788,Involuntary Mooning,primary,0.70
87,INVOLU-788,Monologue Compulsion,primary,0.30
88,PAINTE-404B,Painted Reality Traversal,primary,0.70
89,PAINTE-404B,Reality Anchoring,primary,0.30
90,TIMEMA-433,Time Manipulation,primary,0.70
91,TIMEMA-433,Prophetic Sight,primary,0.30
92,SELFSU-126,Self-Sustenance,primary,0.70
93,IRRESI-147,Irresistible Allure,primary,0.90
94,SEADOM-907,Sea Dominion,primary,0.70
95,SEADOM-907,Tactical Genius,primary,0.20
96,REGENE-998,Regeneration,primary,0.70
97,REGENE-998,Healing Factor,primary,0.30
98,PAINTE-871,Painted Reality Traversal,primary,0.70
99,PAINTE-871,Protean Shapeshifting,primary,0.30

In [7]:
power_seeds_df = spark.read.parquet(os.path.join(warehouse_root, "power_seeds"))
display_scrollable_dataframe(power_seeds_df.limit(100).toPandas())

,power_id,seed_name,role,weight
0,1a4b0ac2f22b,Concept Suppression,secondary,0.2
1,c6034ac92dec,Super Breath,secondary,0.1
2,d5ed082fef54,Concept Suppression,secondary,0.1
3,6c403d9c9dab,Concept Suppression,secondary,0.3
4,c2572da732d2,Super Breath,secondary,0.2
5,9e5010af116a,Concept Suppression,secondary,0.2
6,68a63c565684,Super Breath,secondary,0.3
7,e60dae64583d,Concept Suppression,secondary,0.1
8,07a5bcc58d68,Super Breath,secondary,0.1
9,699f787cd581,Concept Suppression,secondary,0.2
10,4d1ea4fa519a,Super Breath,secondary,0.2
11,2b1026ed0a5f,Concept Suppression,secondary,0.2
12,38317c7a4a95,Super Breath,secondary,0.1
13,03a70ffd51fc,Concept Suppression,secondary,0.3
14,fafd2d1180e3,Super Breath,secondary,0.1
15,813cc5d15a68,Concept Suppression,secondary,0.2
16,f394f7133cb2,Super Breath,secondary,0.1
17,d1c3712b029f,Concept Suppression,secondary,0.2
18,52caa8a85bff,Super Breath,secondary,0.2
19,f8355333529a,Concept Suppression,secondary,0.1
20,e8c3a74c0754,Enhanced Senses,secondary,0.2
21,acf7a1381e2c,Reality Anchoring,secondary,0.1
22,f12a8eb27439,Enhanced Senses,secondary,0.3
23,06cd12c7cc82,Reality Anchoring,secondary,0.2
24,bbf3ae62b9a3,Enhanced Senses,secondary,0.1
25,33fae0863091,Reality Anchoring,secondary,0.3
26,dea3538ee1e9,Enhanced Senses,secondary,0.2
27,d87cafa3f8c9,Reality Anchoring,secondary,0.1
28,1a61daa153eb,Enhanced Senses,secondary,0.4
29,d8d381f5499b,Enhanced Senses,secondary,0.3
30,503a750519de,Reality Anchoring,secondary,0.2
31,fbd15860db68,Enhanced Senses,secondary,0.2
32,9e48675a76cc,Reality Anchoring,secondary,0.1
33,0d1cb57d325f,Enhanced Senses,secondary,0.3
34,39445a926837,Reality Anchoring,secondary,0.2
35,6ffb3441371e,Enhanced Senses,secondary,0.1
36,a0dcb27c028f,Reality Anchoring,secondary,0.3
37,653621ab3665,Enhanced Senses,secondary,0.2
38,5e38088534ec,Reality Anchoring,secondary,0.1
39,b119f677178f,Enhanced Senses,secondary,0.3
40,0f556dbabd96,Imagination Materialization,primary,1.0
41,39f9857b14e2,Imagination Materialization,primary,1.0
42,82c1887a1b90,Imagination Materialization,primary,1.0
43,45d77a279770,Imagination Materialization,primary,1.0
44,9bc0b33676af,Imagination Materialization,primary,1.0
45,d4e75b8a1e0e,Imagination Materialization,primary,1.0
46,df7ad9a91eeb,Imagination Materialization,primary,1.0
47,e8722715ccf0,Imagination Materialization,primary,1.0
48,a5de0de089ed,Imagination Materialization,primary,1.0
49,0b51512d21de,Imagination Materialization,primary,1.0
50,4c4c25b627ed,Imagination Materialization,primary,1.0
51,cb927de28fe8,Imagination Materialization,primary,1.0
52,7a808a95c111,Imagination Materialization,primary,1.0
53,e4859b31b1be,Imagination Materialization,primary,1.0
54,d4beb26452a7,Imagination Materialization,primary,1.0
55,bb6c95d69ffb,Imagination Materialization,primary,1.0
56,6866d03d61e7,Imagination Materialization,primary,1.0
57,203535572645,Imagination Materialization,primary,1.0
58,50fab7063275,Imagination Materialization,primary,1.0
59,306ddafaad47,Imagination Materialization,primary,1.0
60,10efd7920ed1,Pocket Dimension Access,primary,1.0
61,f410dfc2dee5,Pocket Dimension Access,primary,1.0
62,a048042e8d08,Pocket Dimension Access,primary,1.0
63,58e7112332a5,Pocket Dimension Access,primary,1.0
64,04139dd8045c,Pocket Dimension Access,primary,1.0
65,e54d9f49f61f,Pocket Dimension Access,primary,1.0
66,7e25ede440ec,Pocket Dimension Access,primary,1.0
67,9109b0d26b03,Pocket Dimension Access,primary,1.0
68,29e168e86367,Pocket Dimension Access,primary,1.0
69,fb7c7e85d79d,Pocket Dimension Access,primary,1.0
70,49f92b254928,Pocket Dimension Access,primary,1.0
71,95c7f5ac085c,Pocket Dimension Access,primary,1.0
72,c273d20b7b5f,Pocket Dimension Access,primary,1.0
73,ee62a5805ece,Pocket Dimension Access,primary,1.0
74,0f76fa026b94,Pocket Dimension Access,primary,1.0
75,3d0ef78aa848,Pocket Dimension Access,primary,1.0
76,fbd9950e0d9e,Pocket Dimension Access,primary,1.0
77,a7d5661673db,Pocket Dimension Access,primary,1.0
78,8619601e4250,Pocket Dimension Access,primary,1.0
79,96b7c8bf477e,Pocket Dimension Access,primary,1.0
80,bbf89fdb61fc,Enhanced Senses,secondary,0.2
81,e28609b071a0,Self-Sustenance,secondary,0.3
82,266181a986f6,Enhanced Senses,secondary,0.2
83,41a1ce40231d,Enhanced Senses,secondary,0.1
84,f418ab02cd56,Enhanced Senses,secondary,0.2
85,c74ae7b9e699,Self-Sustenance,secondary,0.2
86,1c2ab4ffff6f,Enhanced Senses,secondary,0.2
87,77dc1d8c07a4,Self-Sustenance,secondary,0.1
88,77dc1d8c07a4,Enhanced Senses,secondary,0.1
89,58acd46d9c77,Enhanced Senses,secondary,0.2
90,809201689075,Enhanced Senses,secondary,0.3
91,bd405f36d69c,Self-Sustenance,secondary,0.2
92,49444d646a34,Enhanced Senses,secondary,0.1
93,dad3cd29192d,Self-Sustenance,secondary,0.1
94,bb316fdf4a61,Self-Sustenance,secondary,0.3
95,30124bdf6ac4,Enhanced Senses,secondary,0.3
96,78d41b0931fa,Enhanced Senses,secondary,0.2
97,c319aeb67fbe,Self-Sustenance,secondary,0.2
98,d37a2b6b5848,Self-Sustenance,secondary,0.2
99,7214fd2010f9,Enhanced Senses,secondary,0.4

In [8]:
side_effects_df = spark.read.parquet(os.path.join(warehouse_root, "gene_side_effects"))
display_scrollable_dataframe(side_effects_df.limit(100).toPandas())

,gene_id,side_effect_name,probability,severity,trigger_condition
0,HAMMER-321,Humiliation Trigger,0.40,4,Occurs when attempting to retrieve an object larger than the user's current mass.
1,HAMMER-321,Cynical Deconstruction,0.35,3,Activates if the object retrieved is referenced ironically.
2,HAMMER-321,Moral Whiplash,0.50,5,Triggers when objects of conflicting moral alignment are retrieved consecutively.
3,HAMMER-321,Genre Drift,0.40,3,Triggered if the object retrieved is thematically inconsistent with the environment.
4,OPTICE-847,Moral Whiplash,0.50,3,Activation of energy emission without focus.
5,OPTICE-847,Monologue Compulsion,0.40,4,Upon consecutive emission bursts.
6,OPTICE-847,Rule Awareness,0.30,2,Extended use beyond one hour.
7,OPTICE-847,Escalation Lock,0.60,5,When energy emission encounters force resistance.
8,OPTICE-847,Tragic Irony,0.40,3,Failure to activate force field during critical moments.
9,ELASTI-658,Monologue Compulsion,0.35,3,During extended physical deformation.
10,ELASTI-658,Escalation Lock,0.40,4,Upon stretching beyond initial limit.
11,ELASTI-658,Overacting Penalty,0.45,2,When mimicking complex shapes.
12,ELASTI-658,Rule Awareness,0.30,4,During interactions with Toon Force.
13,PAINTE-652,Rule Awareness,0.35,3,Upon repeated traversal of two-dimensional space.
14,PAINTE-652,Monologue Compulsion,0.40,2,When encountering a previously unknown painting.
15,PAINTE-652,Irony Backfire,0.30,4,After noticing any time discrepancies.
16,PAINTE-652,Narrative Punishment,0.25,5,When attempting to alter a scene intentionally.
17,SEADOM-882,Audience Dependence,0.45,4,Whenever the user attempts to command sea creatures solo.
18,SEADOM-882,Cosmic Boredom,0.35,3,During prolonged use without significant change.
19,SEADOM-882,Irony Backfire,0.40,5,When attempting to manipulate tides to avoid disaster.
20,SUPERS-813,Overacting Penalty,0.50,4,When attempting to exceed Mach 1.
21,SUPERS-813,Cynical Deconstruction,0.35,3,If used in competitive sports.
22,SUPERS-813,Humiliation Trigger,0.40,5,When failing to perceive obstacles at high speeds.
23,SUPERS-813,Escalation Lock,0.60,3,When reaching terminal speed in a crowded environment.
24,IRRESI-582,Genre Drift,0.40,3,Occurs when an individual fails to captivate an intended audience.
25,IRRESI-582,Humiliation Trigger,0.35,4,Triggers under public scrutiny or failure to impress.
26,IRRESI-582,Laughing Exhaustion,0.30,2,Happens when someone is continuously amused by the allure.
27,MATTER-347,Timing Dependency,0.45,4,When manipulating matter across different time phases.
28,MATTER-347,Tragic Irony,0.35,3,When the user's actions result in unintended historical changes.
29,MATTER-347,Cynical Deconstruction,0.32,3,When user attempts philosophical debates while using the power.
30,REGENE-235,Escalation Lock,0.35,4,During repeated use of the gene's function.
31,REGENE-235,Narrative Punishment,0.40,3,When attempting to reverse complex injuries quickly.
32,REGENE-235,Genre Drift,0.50,5,If the gene's abilities are pushed to their temporal limits.
33,IRRESI-985,Humiliation Trigger,0.40,4,Occurs when allure is resisted.
34,IRRESI-985,Irony Backfire,0.35,3,Activates when the desired outcome is achieved but with unintended consequences.
35,IRRESI-985,Self-Deception,0.50,5,Manifests when senses are overwhelmed by allure.
36,IRRESI-985,Hubris,0.33,4,Induced when enhanced allure is mistaken for personal capability.
37,DIVINE-712,Ideological Rigidity,0.35,3,When attempting to summon excessive lightning.
38,DIVINE-712,Escalation Lock,0.40,4,Continuous use over multiple days.
39,DIVINE-712,Monologue Compulsion,0.32,2,Upon successful summoning of lightning.
40,DIVINE-712,Hubris,0.50,5,After overpowering an opponent using divine lightning.
41,POCKET-951,Escalation Lock,0.32,5,When attempting to access larger spaces.
42,POCKET-951,Rule Awareness,0.45,3,During prolonged use of the dimension.
43,POCKET-951,Irony Backfire,0.40,4,When the expected outcome is inverted.
44,TIMEMA-789,Rule Awareness,0.35,4,Occurs when attempting to alter large temporal events.
45,TIMEMA-789,Monologue Compulsion,0.50,3,Activated upon initial temporal manipulation each day.
46,TIMEMA-789,Tragic Irony,0.40,5,Triggered when a temporal alteration results in unintended negative outcomes.
47,MUTANT-537,Cynical Deconstruction,0.35,3,When detecting conflicting genetic patterns.
48,MUTANT-537,Monologue Compulsion,0.40,4,Upon identifying a significant mutation.
49,MUTANT-537,Rule Awareness,0.32,2,During prolonged detection of anomalies.
50,PAINTE-694,Bullshit Sensitivity,0.40,3,Attempting to enter a painted world with false intent.
51,PAINTE-694,Tragic Irony,0.35,5,After a successful traversal into a painted realm.
52,PAINTE-694,Laughing Exhaustion,0.50,4,Prolonged exposure within a painting's boundaries.
53,SEADOM-416,Cosmic Boredom,0.35,3,Extended use of oceanic command powers.
54,SEADOM-416,Irony Backfire,0.40,4,Attempts to control marine life.
55,PAINTE-839,Audience Dependence,0.60,4,When traversing painted realities without spectators.
56,PAINTE-839,Irony Backfire,0.35,3,When attempting to materialize objects that defy reality.
57,PAINTE-839,Laughing Exhaustion,0.40,2,After extended traversal periods.
58,DIVINE-472,Narrative Punishment,0.33,4,When attempting divine acts in mundane settings.
59,DIVINE-472,Laughing Exhaustion,0.45,3,After expending large amounts of divine energy.
60,DIVINE-472,Moral Whiplash,0.37,4,When the morality of actions is questioned.
61,DIVINE-472,Monologue Compulsion,0.40,2,When addressing an audience or crowd.
62,PAINTE-876,Narrative Punishment,0.40,4,When attempting to alter painted reality outcomes.
63,PAINTE-876,Rule Awareness,0.35,3,If user questions the logic of the painted world.
64,PAINTE-876,Laughing Exhaustion,0.50,2,On extended traversal within a painted realm.
65,PAINTE-876,Cosmic Boredom,0.30,5,When user revisits the same painted scene repeatedly.
66,HAMMER-912,Narrative Punishment,0.45,4,When accessing objects beyond personal need.
67,HAMMER-912,Hubris,0.30,3,When attempting repeated access in quick succession.
68,HAMMER-912,Timing Dependency,0.50,5,When retrieving objects during high-stress scenarios.
69,HAMMER-912,Escalation Lock,0.35,4,Upon failure to correctly visualize the desired object.
70,POCKET-964,Boring Companions,0.33,4,Activation of energy within the pocket space.
71,POCKET-964,Escalation Lock,0.45,3,Attempting to modify the pocket dimension's properties.
72,POCKET-964,Laughing Exhaustion,0.40,5,Sustained use of energy projection within the dimension.
73,POCKET-964,Rule Awareness,0.36,2,Cross-dimensional interactions.
74,MATTER-932,Cosmic Boredom,0.40,3,When molecular rearrangements are below critical mass.
75,MATTER-932,Escalation Lock,0.35,4,During rapid successive manipulations.
76,MATTER-932,Tragic Irony,0.38,5,If manipulation fails to yield desired outcome.
77,FLIGHT-483,Timing Dependency,0.40,3,Occurs when asynchronous actions are initiated.
78,FLIGHT-483,Rule Awareness,0.35,2,Triggered during complex maneuvers.
79,FLIGHT-483,Genre Drift,0.50,4,Activated when transitioning between vastly different environments.
80,FLIGHT-483,Overacting Penalty,0.32,3,When aerial stunts are performed with excessive flair.
81,SUPERS-267,Audience Dependence,0.40,4,When performing in front of any sentient audience.
82,SUPERS-267,Moral Whiplash,0.35,3,Upon executing high-speed actions that require quick moral judgement.
83,SUPERS-267,Tragic Irony,0.50,5,During attempts to alter the outcome of unfortunate events.
84,IRRESI-748,Tragic Irony,0.40,4,When influencing decisions beyond personal control.
85,IRRESI-748,Audience Dependence,0.45,3,When allure operates in public settings.
86,IRRESI-748,Genre Drift,0.35,2,When switching narrative contexts.
87,WEATHE-045,Genre Drift,0.40,4,During atmospheric shifts
88,WEATHE-045,Cosmic Boredom,0.35,3,When effects persist too long
89,WEATHE-045,Escalation Lock,0.50,5,In complex weather patterns
90,HEATVI-573,Audience Dependence,0.40,3,When activated in crowded environments.
91,HEATVI-573,Cosmic Boredom,0.35,4,Prolonged use without change in target.
92,HEATVI-573,Humiliation Trigger,0.45,5,When energy misfires or fails to focus.
93,PROTEA-621,Overacting Penalty,0.40,4,Frequent transformations without rest.
94,PROTEA-621,Self-Deception,0.30,3,Prolonged shapeshift into human forms.
95,PROTEA-621,Hubris,0.35,5,Successful manipulation of complex elements.
96,PROTEA-621,Tragic Irony,0.50,3,Attempting to predict outcomes post-transformation.
97,PHASIN-348,Timing Dependency,0.55,4,Occurs if phasing is attempted during erratic temporal conditions.
98,PHASIN-348,Irony Backfire,0.40,3,Activates when the user tries to phase through a wall made of their own fears.
99,PHASIN-348,Narrative Punishment,0.35,5,Triggered when attempting to show off phasing abilities for comedic effect.

## 4. Gene Regulation (Graph)

In [9]:
reg_df = spark.read.parquet(os.path.join(warehouse_root, "gene_regulation"))
display_scrollable_dataframe(reg_df.limit(100).toPandas())

,source_gene_id,target_gene_id,effect,strength
0,PAINTE-642,PAINTE-101,amplify,0.77
1,PAINTE-642,PAINTE-239,destabilize,0.53
2,PAINTE-642,PAINTE-340,gate,0.42
3,PAINTE-642,PAINTE-445,suppress,0.38
4,PAINTE-642,PAINTE-556,amplify,0.49
5,PAINTE-642,PAINTE-662,suppress,0.61
6,PAINTE-642,PAINTE-774,destabilize,0.65
7,PAINTE-642,PAINTE-885,gate,0.57
8,PAINTE-642,PAINTE-920,amplify,0.71
9,PAINTE-642,PAINTE-301,suppress,0.35
10,PAINTE-642,PAINTE-412,destabilize,0.69
11,PAINTE-642,PAINTE-523,gate,0.44
12,PAINTE-642,PAINTE-634,amplify,0.62
13,PAINTE-642,PAINTE-745,suppress,0.55
14,PAINTE-642,PAINTE-856,destabilize,0.68
15,PAINTE-642,PAINTE-967,gate,0.47
16,PAINTE-642,PAINTE-208,amplify,0.58
17,PAINTE-642,PAINTE-319,suppress,0.40
18,PAINTE-642,PAINTE-430,destabilize,0.51
19,PAINTE-642,PAINTE-541,gate,0.63
20,PAINTE-642,PAINTE-652,amplify,0.45
21,PAINTE-642,PAINTE-763,suppress,0.55
22,PAINTE-642,PAINTE-874,destabilize,0.66
23,PAINTE-642,PAINTE-985,gate,0.48
24,PAINTE-642,PAINTE-096,amplify,0.60
25,PAINTE-642,PAINTE-107,suppress,0.52
26,PAINTE-642,PAINTE-218,destabilize,0.54
27,PAINTE-642,PAINTE-329,gate,0.39
28,PAINTE-642,PAINTE-440,amplify,0.69
29,PAINTE-642,PAINTE-551,suppress,0.37
30,HAMMER-480,HAMMER-100,amplify,0.62
31,HAMMER-480,HAMMER-101,gate,0.45
32,HAMMER-480,HAMMER-102,suppress,0.38
33,HAMMER-480,HAMMER-103,amplify,0.51
34,HAMMER-480,HAMMER-104,destabilize,0.37
35,HAMMER-480,HAMMER-105,gate,0.55
36,HAMMER-480,HAMMER-106,amplify,0.72
37,HAMMER-480,HAMMER-107,suppress,0.57
38,HAMMER-480,HAMMER-108,destabilize,0.40
39,HAMMER-480,HAMMER-109,amplify,0.64
40,HAMMER-480,HAMMER-110,suppress,0.46
41,HAMMER-480,HAMMER-111,gate,0.50
42,HAMMER-480,HAMMER-112,amplify,0.68
43,HAMMER-480,HAMMER-113,suppress,0.47
44,HAMMER-480,HAMMER-114,destabilize,0.42
45,HAMMER-480,HAMMER-115,amplify,0.61
46,HAMMER-480,HAMMER-116,gate,0.54
47,HAMMER-480,HAMMER-117,suppress,0.44
48,HAMMER-480,HAMMER-118,amplify,0.67
49,HAMMER-480,HAMMER-119,destabilize,0.36
50,HAMMER-480,HAMMER-120,gate,0.53
51,HAMMER-480,HAMMER-121,amplify,0.69
52,HAMMER-480,HAMMER-122,suppress,0.43
53,HAMMER-480,HAMMER-123,destabilize,0.41
54,HAMMER-480,HAMMER-124,amplify,0.65
55,HAMMER-480,HAMMER-125,gate,0.56
56,HAMMER-480,HAMMER-126,suppress,0.48
57,HAMMER-480,HAMMER-127,amplify,0.70
58,HAMMER-480,HAMMER-128,destabilize,0.39
59,HAMMER-480,HAMMER-129,gate,0.52
60,OPTICE-130,OPTICE-101,amplify,0.65
61,OPTICE-130,OPTICE-102,suppress,0.45
62,OPTICE-130,PHASE-112,gate,0.55
63,OPTICE-130,SPEED-221,destabilize,0.38
64,OPTICE-130,OPTICE-133,amplify,0.75
65,OPTICE-130,SENSE-330,suppress,0.42
66,OPTICE-130,INVISI-440,suppress,0.36
67,OPTICE-130,PROBA-550,amplify,0.58
68,OPTICE-130,DIVINE-660,amplify,0.49
69,OPTICE-130,TELEK-770,gate,0.55
70,OPTICE-130,SIZE-880,destabilize,0.37
71,OPTICE-130,UNDER-990,suppress,0.53
72,OPTICE-130,PHASE-121,amplify,0.66
73,OPTICE-130,SPEED-222,gate,0.41
74,OPTICE-130,OPTICE-134,destabilize,0.47
75,OPTICE-130,SENSE-331,amplify,0.57
76,OPTICE-130,INVISI-441,destabilize,0.39
77,OPTICE-130,PROBA-551,suppress,0.44
78,OPTICE-130,TELEK-771,suppress,0.46
79,OPTICE-130,SIZE-881,amplify,0.62
80,OPTICE-130,UNDER-991,destabilize,0.35
81,OPTICE-130,OPTICE-135,gate,0.54
82,OPTICE-130,SENSE-332,suppress,0.43
83,OPTICE-130,INVISI-442,amplify,0.59
84,OPTICE-130,PROBA-552,gate,0.49
85,OPTICE-130,DIVINE-661,destabilize,0.61
86,OPTICE-130,TELEK-772,amplify,0.78
87,OPTICE-130,SIZE-882,suppress,0.37
88,OPTICE-130,UNDER-992,amplify,0.60
89,OPTICE-130,PHASE-122,destabilize,0.57
90,MYSTIC-954,MYSTIC-821,amplify,0.68
91,MYSTIC-954,MYSTIC-403,suppress,0.42
92,MYSTIC-954,MYSTIC-777,gate,0.51
93,MYSTIC-954,MYSTIC-332,destabilize,0.36
94,MYSTIC-954,MYSTIC-201,amplify,0.48
95,MYSTIC-954,MYSTIC-105,suppress,0.62
96,MYSTIC-954,MYSTIC-909,amplify,0.58
97,MYSTIC-954,MYSTIC-654,suppress,0.35
98,MYSTIC-954,MYSTIC-010,gate,0.49
99,MYSTIC-954,MYSTIC-117,destabilize,0.47

## 5. Sanity Export (Excel)
Exporting top 10 rows of each table to `data/sanity/warehouse_top10.xlsx`.

In [10]:
sanity_dir = os.path.join(stage_root, "sanity")
os.makedirs(sanity_dir, exist_ok=True)
out_path = os.path.join(sanity_dir, "warehouse_top10.xlsx")

# Forced Deletion to ensure freshness
if os.path.exists(out_path):
    try:
        os.remove(out_path)
        print(f"Deleted existing file: {out_path}")
    except OSError as e:
        print(f"Warning: Could not delete existing file {out_path}: {e}")

print(f"Exporting to {out_path}...")

with pd.ExcelWriter(out_path, mode='w') as writer:
    genes_df.limit(10).toPandas().to_excel(writer, sheet_name="Genes", index=False)
    powers_df.limit(10).toPandas().to_excel(writer, sheet_name="Powers", index=False)
    gene_seeds_df.limit(10).toPandas().to_excel(writer, sheet_name="Gene Seeds", index=False)
    power_seeds_df.limit(10).toPandas().to_excel(writer, sheet_name="Power Seeds", index=False)
    side_effects_df.limit(10).toPandas().to_excel(writer, sheet_name="Gene Side Effects", index=False)
    reg_df.limit(10).toPandas().to_excel(writer, sheet_name="Regulation", index=False)

print("Export Complete. File is fresh.")

Exporting to /home/gideon/tmp/super_powers/data/sanity/warehouse_top10.xlsx...
Export Complete. File is fresh.